{{- if .Values.consumer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saferwall.consumer.fullname" . }}
  labels:
    app: {{ include "saferwall.consumer.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "saferwall.consumer.fullname" . }}
  replicas:  {{ .Values.consumer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "saferwall.consumer.fullname" . }}
    spec:
      {{ if eq .Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.consumer.name }}"
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          volumeMounts:
          - name: samples
            mountPath: /samples
          - name:  {{ $.Release.Name }}-consumer-configmap-volume
            mountPath: /consumer/configs/
          env:
            - name: ENVIRONMENT
              value: "prod"
      volumes:
      - name: samples
        persistentVolumeClaim:
          claimName: {{ include "saferwall.fullname" . }}-samples
      - name: {{ $.Release.Name }}-consumer-configmap-volume
        configMap:
          name: {{ include "saferwall.consumer.fullname" . }}
          items:
            - key: consumer_conf
              path: saferwall.prod.toml
      initContainers:
        - name: wait-for-couchbase
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "pod"
            - "-lapp=couchbase"
        - name: wait-for-backend
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "pod"
            - "-ltier=backend"

{{- end }}
