{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saferwall.frontend.fullname" . }}
  labels:
    app: {{ include "saferwall.frontend.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "saferwall.frontend.fullname" . }}
  replicas:  {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "saferwall.frontend.fullname" . }}
    spec:
      {{ if eq .Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.frontend.name }}"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          {{ if eq .Values.global.localRegistryServer true }}
          imagePullPolicy: Never
          {{ else }}
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: VUE_APP_BACKEND_HOST
              value: "{{ .Values.backendHostname }}"
{{- end }}