# Use this docker-compose file to setup the test environment before running the tests.

services:
  couchbase:
    image: couchbase/server:7.2.0
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

  nsqlookupd:
    image: nsqio/nsq:v1.2.1
    command: /nsqlookupd --log-level=error
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=${EXTERNAL_IP} --max-msg-size=1413820683 --log-level=error
    environment:
      - "EXTERNAL_IP=${EXTERNAL_IP}"
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    image: nsqio/nsq:v1.2.1
    command: >
      /nsqadmin --lookupd-http-address=nsqlookupd:4161 --log-level=error
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  webapis:
    image: saferwall/webapis:latest
    ports:
      - "8080:8080"
    environment:
      - SFW_WEBAPIS_DEPLOYMENT_KIND=dev
    entrypoint:
      [
        /saferwall/server,
        -config,
        /saferwall/conf/,
        -db,
        /saferwall/db,
        -tpl,
        /saferwall/templates,
      ]
    restart: always

  ui:
    image: saferwall/ui:latest
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: http://localhost:8080/v1/
      PUBLIC_AVATAR_API_URL: https://avatar.saferwall.com/{username}
    depends_on:
      - webapis

  ml:
    image: saferwall/ml-pipeline:latest
    ports:
      - "8001:8001"

  orchestrator:
    image: saferwall/orchestrator:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/orchestrator-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples
      - /saferwall:/saferwall/storage

  aggregator:
    image: saferwall/aggregator:latest
    depends_on:
      - couchbase
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/aggregator-svc, -config, /saferwall/conf/]
    restart: always

  postprocessor:
    image: saferwall/postprocessor:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/postprocessor-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples
    restart: always

  pe:
    image: saferwall/pe:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/pe-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  meta:
    image: saferwall/gometa:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/meta-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  avira:
    image: saferwall/goavira:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/avira-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  clamav:
    image: saferwall/goclamav:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/clamav-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  comodo:
    image: saferwall/gocomodo:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/comodo-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  windefender:
    image: saferwall/gowindefender:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/windefender-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

  sandbox:
    image: saferwall/sandbox:latest
    environment:
      - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/sandbox-svc, -config, /saferwall/conf/]
    volumes:
      - /samples:/samples

volumes:
  minio_data: null
  couchbase_data: null
