# Log level verbosity.
log_level = "debug"
# Address ofthe server that host the machine learning pipeline.
ml_address = "http://ml-pipeline:8000"
# Shared volume between all microservices.
shared_volume = "/samples"

[producer]
# The data source name (DSN) for connecting to the broker server (NSQD).
nsqd = "nsqd:4150"
# Topic name to produce to.
topic = "topic-aggregator"

[consumer]
# The data source name (DSN) for connecting to the service discovery server
# (NSQLookupD).
lookupds = ["nsqlookupd:4161"]
# Topic name to consume from.
topic = "topic-postprocessor"
# Channel name used in conjunction with topic name.
channel = "chan-postprocessor"
# The number of concurrent workers to process the jobs.
concurrency = 1

[db]
# DSN for connecting to the database.
server = "couchbase://couchbase"
# Username used to access the db.
username = "Administrator"
# Password used to access the db.
password = "password"
# Name of the couchbase bucket.
bucket_name = "sfw"
