# This file needs to be edited !

[backend]
address = 'http://{{ include "saferwall.fullname" . }}-backend'
admin_user = "Administrator"
admin_pwd = "password"

[consumer]
# Possible values "panic", "fatal", "error", "warn", "info", "debug", "trace"
log_level = "warn"
download_dir = "/samples"

[ml]
address = 'http://{{ include "saferwall.fullname" . }}-ml'

[nsq]
lookupds = [
{{ $lookupdFullName := printf "%s-nsq-%s" .Release.Name .Values.nsq.nsqlookupd.name -}}
{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.nsq.nsqlookupd.replicaCount))) -}}
    "{{ $lookupdFullName }}-{{ $i }}.{{ $lookupdFullName }}:4161",
{{- end }}]

[minio]
endpoint = '{{ printf "%s-minio" .Release.Name }}:9000'
seckey = "{{ .Values.minio.secretKey }}"
accesskey = "{{ .Values.minio.accessKey }}"
spacename = "{{ .Values.minio.spacename }}"
ssl = false

[multiav]
{{- $root := . -}}
{{- range $av, $value := .Values.multiav.vendors }}
  [multiav.{{ $av }}]
  enabled = {{ $value.enabled }}
  addr = "{{ include "saferwall.fullname" $root }}-multiav-{{ $av }}:50051"
{{- end }}
