{{- if .Values.sandbox.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "saferwall.fullname" . }}-pe
  labels:
    app.kubernetes.io/name: {{ template "saferwall.name" . }}-pe
{{ include "saferwall.labels" . | indent 4 }}
data:
  sandbox_conf: {{ tpl (.Files.Get "files/sandbox.toml") . | quote }}
{{- end }}