### Config sample, needs to be edited.

[ui]
address = "http://localhost:8081"

[app]
address = "<host:port>"
debug = true
tmp_samples = "/tmp/samples"
max_file_size = 64000000 # 64MB
admin_user = "<admin>"
admin_pwd = "<password>"
admin_email = "<admin@company.com>"

[db]
server = "couchbase://<host>"
username = "<username>"
password = "<password>"

[nsq]
addr = "localhost:4150"

[minio]
endpoint = "localhost:9000"
seckey = "<seckey>"
accesskey = "<accesskey>"
spacename = "samples"
avatarspace = "images"
ssl = false

[auth]
signkey = "<signkey>"

[smtp]
server = "smtp.example.com"
port = 465
user =  "user@example.com"
password = "password"
identity =  "identity"
sender =  "sender@example.com"