name: Test Helm Charts
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-on-minikube:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (kubectl/kind/helm/vbox/minikube)
        run: |
          git clone https://github.com/saferwall/saferwall.git
          cd saferwall
          make vbox-install
          make minikube-install
          make kubectl-install
          make helm-install

      - name: Create Minikube cluster
        run: |
            cd saferwall
            make minikube-down || true
            make minikube-up

      - name: Helm Release
        run: |
          cd saferwall
          make helm-release

      - name: Wait for pods to be ready
        run: kubectl wait --for=condition=Ready pods --all --timeout=360s

      - name: Add DNS entry
        run: echo "$(minikube ip) mysaferwall.com api.mysaferwall.com" | sudo tee -a /etc/hosts

      - name: Check success
        run: |
            curl -k -I https://mysaferwall.com
            curl -k -I -X GET https://api.mysaferwall.com/v1/users/Administrator

  deploy-on-kind:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (kubectl/kind/helm)
        run: |
          git clone https://github.com/saferwall/saferwall.git
          cd saferwall
          make kubectl-install
          make kind-install
          make helm-install

      - name: Create Kind cluster
        run: |
          cd saferwall
          make kind-up

      - name: Helm Release
        run: |
          cd saferwall
          make helm-release

      - name: Wait for pods to be ready
        run: kubectl wait --for=condition=Ready pods --all --timeout=600s

      - name: Add DNS entry
        run: echo "127.0.0.1 mysaferwall.com api.mysaferwall.com" | sudo tee -a /etc/hosts

      - name: Check success
        run: |
          curl -k -I https://mysaferwall.com
          curl -k -I -X GET https://api.mysaferwall.com/v1/users/Administrator
