name: Test Helm Charts
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy-on-kind:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (kubectl/kind/helm)
        run: |
          git clone https://github.com/saferwall/saferwall.git
          cd saferwall
          make
          make kubectl/install
          make kind/install
          make helm/install

      - name: Create Kind cluster
        run: |
          cd saferwall
          make kind/up

      - name: Helm Release
        run: |
          cd saferwall
          make helm/release

      - name: Wait for pods to be ready
        run: kubectl wait --for=condition=Ready pods --all --timeout=900s

      - name: Add DNS entry
        run: echo "127.0.0.1 mysaferwall.com api.mysaferwall.com" | sudo tee -a /etc/hosts

      - name: Check success
        run: |
            curl -k -I https://mysaferwall.com
            curl -k -X POST https://api.mysaferwall.com/v1/users/ \
              -H 'Content-Type: application/json' \
              -d '{"username":"mrrobot","password":"password", "email": "mrrobot@mysaferwall.com"}'
            curl -k -I -X GET https://api.mysaferwall.com/v1/users/mrrobot

      - name: Cleanup
        run: |
          cd saferwall
          make kind-down
